# COMMENTS!


rule all:
	input:
		'output/{data}.txt'


FILES = ['features','folds','labels']

rule get_data:
	output:
		"input/{data}.rda"
	shell:
		"""
		wget
		"""


rule convert_data:
	input:
		"input/{data}.rda"
	output:
		"input/{data}.txt"
	script:
		"scripts/convert_data.R"

rule get_features:
	input:
		"input/{data}.txt"
	output:
		expand("output/{{data}}.{file}.txt", file=FILES)
	shell:
		"""
		cut -d$'\t' -f 1-26 < {input} > {output[0]};
		cut -f27 < {input} > {output[1]};
		cut -f28 < {input} > {output[2]}
		"""


rule generate_parsmurf_config:
	input:
		features="output/{data}.features.txt",
		folds="output/{data}.folds.txt",
		labels="output/{data}.labels.txt",
		scaffold="data/scaffolds.json"
	output:
		config="output/{data}.json"
	params:
		name="{name}",
		output="output/{data}.txt"
	script:
		"scripts/generate_parsmurf_config.py"

#i=lambda wc: config[wc.run]|['i']

rule run_parSMURF:
	input:
		expand("output/{{data}}.{file}.txt", file=FILES),
		config="output/{data}.json"
	output:
		'output/{data}.txt'
	shell:
		"""
		parSMURF1 --cfg {input.config}
		"""
