configfile: "Utils/features_config.json"

rule all:
	output:


rule get_feature_cpgIslandExt:
	input:
	output:
		path = "input/features/{data}/cpgIslandExt/cpgIslandExt.txt.gz"
	params:
		link=lambda wildcards, output: config[wildcards.data]['GCContent']+'cpgIslandExt.txt.gz'
	shell:
		"""
		echo 'rsync -a -P rsync://{params.link} {output.path}' ;
		"""


rule get_feature_priPhyloP46way:
	input:
	output:
		 path = temp("input/features/{data}/priPhyloP46way/rsync.txt")

	params:
		link = lambda wildcards, output: config[wildcards.data]['priPhyloP46way'],
		filter = 'chr[0-9]|chrX|chrY.*.phyloP30way.wigFix.gz'
	script:
		"scripts/generate_rsync.py"
#	shell:
#		"""
#		ein Beispiel von einem anderen Feature
#		bash input/features/hg38/cpgIslandExt/rsync.sh
#		"""
